# Generated by Django 5.2.4 on 2025-07-22 01:08

import app_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=app_api.models.upload_path),
        ),
    ]
