# Generated by Django 5.2.4 on 2025-08-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_projects.projectmanager'),
            preserve_default=False,
        ),
    ]
