# Generated by Django 5.2.4 on 2025-08-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_project_projectmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_projects.projectmanager'),
        ),
    ]
