# Generated by Django 5.2.4 on 2025-07-27 06:06

import app_employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_employees.models.emp_upload_path)),
            ],
        ),
    ]
