# Generated by Django 5.2.4 on 2025-07-28 00:54

import app_employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0003_alter_employee_designation_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_employees.models.emp_upload_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
