# Generated by Django 5.2.4 on 2025-07-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0004_employee_image_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee/'),
        ),
    ]
