# Generated by Django 5.2.4 on 2025-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_alter_post_banner_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
